// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEIxMp000GxMWneCMqRZMQgGgLt1ahq7U',
    appId: '1:1009809943678:web:ed8b786840793cd0fe7c2f',
    messagingSenderId: '1009809943678',
    projectId: 'driveclone-7ea73',
    authDomain: 'driveclone-7ea73.firebaseapp.com',
    storageBucket: 'driveclone-7ea73.appspot.com',
    measurementId: 'G-94F6BBXX3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfZrAkGaz-RWBYSWdzHHHHEwrVyIsOMlE',
    appId: '1:1009809943678:android:3f257b5f02e1fc35fe7c2f',
    messagingSenderId: '1009809943678',
    projectId: 'driveclone-7ea73',
    storageBucket: 'driveclone-7ea73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBr95jsPAUk5Q_lmWxhFu-N1Cce4IJAp4',
    appId: '1:1009809943678:ios:d468897e9e8c63e9fe7c2f',
    messagingSenderId: '1009809943678',
    projectId: 'driveclone-7ea73',
    storageBucket: 'driveclone-7ea73.appspot.com',
    iosBundleId: 'com.example.driveclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBr95jsPAUk5Q_lmWxhFu-N1Cce4IJAp4',
    appId: '1:1009809943678:ios:642bbe5c621e8cd8fe7c2f',
    messagingSenderId: '1009809943678',
    projectId: 'driveclone-7ea73',
    storageBucket: 'driveclone-7ea73.appspot.com',
    iosBundleId: 'com.example.driveclone.RunnerTests',
  );
}
